### ISSUE TITLE
Add owl:sameAs to https://www.iana.org/assignments/media-types/XXX IRIs

### ISSUE THREAD

**Issue by jakubklimek** [nicholascar/mediatypes-dataset#1]
Since you suggest to use the w3id.org IRIs for media types, could you also include `owl:sameAs` links to the IRIs currently used by DCAT(-AP) implementations based on the official MIME-Type IRIs such as `https://www.iana.org/assignments/media-types/text/turtle` for Turtle?

**Comment by nicholascar** [comment]
Yes, will do.

**Comment by nicholascar** [comment]
Added at https://github.com/nicholascar/mediatypes-dataset/commit/8c0a36c3c0874afa6de2e87d63713eeb2a75c382
